In [1]:
import numpy as np

In [2]:
data = np.array([[1,2],[3,4],[5,6]])

In [3]:
type(data)

numpy.ndarray

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
data.ndim

2

In [6]:
data.shape

(3, 2)

In [7]:
data.size

6

In [8]:
data.dtype

dtype('int64')

In [9]:
data.nbytes

48

In [10]:
np.array([1,2,3],dtype=np.int)

array([1, 2, 3])

In [13]:
np.array([1,2,3],dtype=np.float)

array([1., 2., 3.])

In [14]:
np.array([1,2,3],dtype=np.complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [15]:
data = np.array([1,2,3],dtype=np.float)
data

array([1., 2., 3.])

In [16]:
data.dtype

dtype('float64')

In [17]:
data = np.array(data,dtype=np.int)
data.dtype

dtype('int64')

In [18]:
data

array([1, 2, 3])

In [19]:
data = np.array([1,2,3],dtype=np.float)
data

array([1., 2., 3.])